### PR TITLE
[WIP] Archive split

### PR DESCRIPTION
**Pull request by webdesserts**
This pull request attempts the archive split discussed in #41. It is currently a work in progress.

The core side of the split can be found at [webdesserts/beaker-core](https://github.com/webdesserts/beaker-core)

Some things I'd like feedback on:

- How would you like to name the separate archives? One thing that I noticed is that it was a bit confusing to clone down and talk about `beaker` and `beaker-core`. Am I working on "the core of the Beaker Browser" or the "core of the Rotonde Beaker Browser Portal"?
- Where does the documentation go? My initial thought is that this might be a one time fork for most users. If our documentation is in the portal repo, then that documentation is going to immediately go out of date for them. I was thinking of putting the bulk of the documentation in the "core" and then having a Readme that links to the "core" documentation in the "portal" repo.
- Should we supply one `<script>` or multiple? The internals of Rotonde may drastically change in the future, by having an individual script for each file, we are exposing implementation details to users and limiting our ability to change that structure at a later time.
- In the same line of thought as the above, how do you feel about combining `<link>` files?
- What browsers are we supporting? Specifically, should Rotonde eventually be accessible (maybe in some dumbed down version) via normal http browsers? One motivation for this question is that if Rotonde is focused solely on Beaker Browser, we can use some of the latest Chrome APIs. For example `<script type="module">` is currently available in Chrome stable and I imagine it would be coming here soon for Beaker as well. This could help solve the "multi script" problem mentioned above without having to rely on a build system.
- How would you like me to pass the `core` off to you? Currently my pull requests references a dat url that I'm only broadcasting locally. I can rehost it temporarily, but I figure y'all might want to take ownship of it anyway. Any preference on how I pass that off?

Cheers 🍸

### CODE REVIEW

**Comment by neauoire** [comment]
Okay, let's not merge this right away. I actually want to users to clone a different repo, this way it will be a gradual implementation that won't break anything for anyone. Let me try to answer some of your questions :)

**Comment by neauoire** [comment]
Let's move over to: https://github.com/Rotonde/client

**Comment by pfrazee** [comment]
I'm going to follow the client repo and discussions about this, since this is going to be a common pattern for apps and beaker may need to add some tools to help. Feel free to @ me with questions.

**Comment by neauoire** [comment]
Okay, so I picked up your fork. I found an elegant way that will not require for the user to update it's scripts. I will use what you've built and create the first commit on /client tonight. We can go from there, this way of building things is the future, I'm excited to see where this leads.

**Comment by webdesserts** [comment]
@neauoire OK looking forward to seeing what you got 👍🏼

**Pull request closed without merging**
