### PR TITLE
Allow users to post images other than .jpg

### PR DESCRIPTION
**Pull request by louiscenter**
`entry.js` currently assumes any images posted will use the extension `.jpg`. If this PR was merged, for a user to post an image, they would post the following:

```
Here is a beautiful picture >> image.jpg
```

Of course, the `.jpg` assumption might be entirely deliberate, as this would then allow users to post things like `.gif` images which can be large in size and distracting/slow to the UI.

The first image I tried posting was a screenshot of my desktop, which was in `.png` format. This didn't work obviously, which then motivated me to make this PR.

If the `.jpg` limitation is deliberate, I understand. Maybe we could instead make this more limitation obvious to the user within the UI, or the documentation.

### CODE REVIEW

**Comment by neauoire** [comment]
I'm onboard with this, it will also allow people to share other formats such as gifv/mp4(which I love) and so on.

**Comment by louiscenter** [comment]
@neauoire I could do another PR that allows for video based formats? I'm not sure if `` elements can support playing videos.

**Comment by lsjroberts** [comment]
Worth pointing out that this will have broken historical posts, so we could pop in default to `.jpg` if no extension included. I'm out the rest of today but can do it tomorrow if needed.

**Comment by cblgh** [comment]
@lsjroberts i just fixed that in https://github.com/Rotonde/beaker/commit/d1798be9c847a93028b031e49ebcea40dbbb2d3b :3

**Pull request merged**
