### PR TITLE
Format code with Prettier

### PR DESCRIPTION
**Pull request by maxdeviant**
Look how pretty ✨

### CODE REVIEW

**Comment by neauoire** [comment]
AAArgh shiet, I hadn't seen this. Could you run it again over my shitty spaghetti code?
I'll run it before committing form now on 🥉

**Comment by maxdeviant** [comment]
@neauoire All good! There are ways to have it run automatically on commit, so I can look into getting those set up as well.

**Comment by maxdeviant** [comment]
@neauoire This should be ready to go now.

**Comment by lsjroberts** [comment]
@maxdeviant I use https://github.com/okonet/lint-staged as it is cross-platform and easy to setup

**Pull request merged**
