### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR adds the Contributor Covenant Code of Conduct, as suggested in #49.

### CODE REVIEW

**Comment by lsjroberts** [comment]
I'm +1 on this, but would like to get @neauoire's opinion before merging.

**Comment by maxdeviant** [comment]
Especially since it's his email in the CoC :smile:

**Comment by neauoire** [comment]
I love this, thank you for writing it :)

**Comment by maxdeviant** [comment]
@neauoire Unfortunately I can't take the credit: https://www.contributor-covenant.org/ :smile:

**Pull request merged**
